apiVersion: pmem-csi.intel.com/v1alpha1
kind: Deployment
metadata:
  name: pmem-deployment
spec:
  pmemPercentage: 50
  deviceMode: lvm
  controllerResources:
    requests:
      cpu: "200m"
      memory: "100Mi"
  nodeResources:
    requests:
      cpu: "200m"
      memory: "100Mi"
