apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pmem-csi-sc-ext4-wffc
parameters:
  csi.storage.k8s.io/fstype: ext4
  eraseafter: "true"
provisioner: pmem-csi.intel.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
